---
language: python
install:
  - pip install coveralls
python:
  - "2.7"
  - "3.3"

# --source specifies what packages to cover, you probably want to use that option
script:
    coverage run --source=rhetoric setup.py test

after_success: coveralls
